config/routes.rb
EightyThousandHours::Application.routes.draw do
  resources :authentications do
    get 'create_new_account', :on => :collection
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts',
                     :controllers => { :sessions => 'sessions',
                                       :registrations => 'registrations' }

  match '/accounts/merge' => 'users#merge'

  match '/blog/feed.atom' => 'blog_posts#feed', :as => :feed, :defaults => { :format => 'atom' }
  resources :blog_posts, :path => 'blog' do
    collection do
      get 'drafts'
      get :tag
      get :author
      get :vote
    end
  end

  resources :discussion_posts, :path => 'discussion' do
    collection do
      get 'drafts'
    end
  end

  resources :comments

  resources :causes, :only => [:new,:create,:show,:index], :path => 'donations/causes'
  resources :donations, :only => [:new,:create,:update,:show,:index,:edit]

  resources :votes, :only => [:new,:create,:delete]

  resources :supporters, :only => [:new, :create], :path => 'show-your-support'
  match 'show-your-support' => 'supporters#new'

  resources :chat_requests, :only => [:new,:create], :path => 'chat-to-us'
  match 'chat-to-us' => 'chat_requests#new'

  resources :career_advice_requests, :only => [:new,:create], :path => 'request-a-career-advice-session'
  match 'request-a-career-advice-session' => 'career_advice_requests#new'

  resources :endorsements, :only =>[:index]
  resources :videos, :only =>[:index]

  resources :etkh_profiles, :path => "members", :only => [:new,:create,:show,:index] do
    collection do
      post 'search'
    end
  end

  resources :users, :path => 'accounts', :only => [:show,:edit,:update,:destroy] do
    resources :etkh_profiles 
    member do
      get 'posts'
    end
    collection do
      get 'all'
      get 'email_list'
    end
  end

  resources :surveys, :only => [:show]

  # pages which don't live in the database as they can't be
  # converted to pure Markdown
  match 'events'             => 'info#events'
  match 'events/past-events' => 'info#past_events'
 
  # pages from old HIC site
  match 'ethical-career'                => 'info#banker_vs_aid_worker'
  match 'old-ethical-career'            => 'info#ethical_career'
  match 'what-you-can-do'               => 'info#what_you_can_do'
  match 'what-you-can-do/my-donations'  => 'info#my_donations'
  match 'what-we-do'                    => 'info#what_we_do'

  # all other pages are stored as Markdown in the database
  root :to => 'pages#show', :id => "home"
  match 'search'        => 'pages#search'
  match 'mailing-list'  => 'pages#mailing_list'
  match 'sitemap'       => 'pages#sitemap'
  match 'survey_test'   => 'pages#survey_test'
  resources :pages
  resources :pages, :path => '/', :only => [:show]
end

app/models/etkh_profile.rb
class EtkhProfile < ActiveRecord::Base
  belongs_to :user

  attr_accessible :background,
                  :career_plans,
                  :confirmed,
                  :inspiration,
                  :interesting_fact,
                  :occupation,
                  :organisation,
                  :organisation_role,
                  :doing_good_inspiring,
                  :doing_good_research,
                  :doing_good_philanthropy,
                  :doing_good_prophilanthropy,
                  :doing_good_innovating,
                  :doing_good_improving,
                  :public_profile,
                  :skills_knowledge_share,
                  :skills_knowledge_learn,
                  :causes_comment,
                  :profile_option_cause_ids,
                  :activities_comment,
                  :profile_option_activity_ids,
                  :donation_percentage,
                  :donation_percentage_optout

  # now we can access @etkh_profile.name etc.
  delegate :name, :name=, 
           :location, :location=,
           :to => :user

  scope :newest, order("created_at DESC")

  has_and_belongs_to_many :profile_option_causes
  has_and_belongs_to_many :profile_option_activities
end

app/controllers/etkh_profiles_controller.rb
class EtkhProfilesController < ApplicationController
  load_and_authorize_resource :only => [:new,:create,:edit,:update,:destroy]

  def new
    if current_user.nil?
      raise CanCan::AccessDenied.new("You need to create an account first!", :create, EtkhProfile)
    end

    if current_user.etkh_profile.nil?
      # create a new profile for the user
      @etkh_profile = EtkhProfile.new
      current_user.etkh_profile = @etkh_profile

      # fire off an email informing 80k team (join@80k..)
      EtkhProfileMailer.tell_team(current_user).deliver!

      # send an email to the user
      EtkhProfileMailer.thank_applicant(current_user).deliver!

      # add name to 'show your support'
      @supporter = Supporter.new(:name => current_user.name, :email => current_user.email)
      @supporter.save

      # new profile should redirect here when done
      session[:next_page] = '/surveys/members-survey'
    else
      # user already has a profile but has visited /members/new
      render 'edit'
    end
    @menu_root = "Membership"
    @menu_current = "Join now"
  end

  def index
    get_grouped_profiles

    @menu_root = "Our community"
    @menu_current = "Our members"
    @title = "Members"
  end

  def get_grouped_profiles
    @profiles = EtkhProfile.all.to_a.sort_by{|p| p.user.name[0].upcase }
    @grouped_profiles = @profiles.group_by{ |profile| profile.user.name[0].upcase }
    @newest_profiles = EtkhProfile.newest.limit(8)
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @donations = @user.donations.confirmed
    @profile = @user.etkh_profile

    @menu_root = "Our community"
    @menu_current = "Our members"
  end

  def destroy
    profile = EtkhProfiles.find( params[:id] )
    if profile.destroy
      flash[:"alert-success"] = "Deleted profile"
    else
      flash[:"alert-error"] = "Failed to delete profile!"
    end
    redirect_to users_path
  end

  def edit
    @etkh_profile = current_user.etkh_profile
  end

  def update
    if current_user.update_attributes(params[:user])
      flash[:"alert-success"] = "Your profile was successfully updated."
      if session[:next_page]
        next_page = session[:next_page]
        session[:next_page] = nil
        redirect_to( next_page )
      else
        redirect_to( etkh_profile_path( current_user ) )
      end
    else
      render :action => "edit"
    end
  end

  def search
    @user = User.find_by_name(params[:name])
    if @user
      redirect_to etkh_profile_path(@user)
    else
      flash[:"alert-error"] = "Couldn't find #{params[:name]}!"
      redirect_to :action => :index
    end
  end

end

app/views/etkh_profiles/_backup_form.html.haml
= simple_form_for(current_user, url: user_etkh_profile_url(current_user, current_user.etkh_profile),
                                html: { class: 'form-horizontal' },
                                defaults: { input_html: { class: 'span4' } }  ) do |f|
  = f.fields_for :etkh_profile, defaults: { input_html: { class: 'span4' } } do |ep|
    = field_set_tag "Public profile fields: will be visible at 80000hours.org/members" do
      = f.input :location
      = ep.input :organisation, label: "Your organisations, separated by commas", :placeholder => "i.e. universities and companies you’re a member of"
      = ep.input :background,   label: "Tell the other members of 80,000 Hours a little about yourself. What are you career plans, and how have they changed? What do you currently do? Why did you join 80,000 Hours?", :input_html => {:rows=>'10'} 

      %label
        Which #{link_to 'high impact activities', '/faq#activities', :target => '_blank' } do you intend to be involved in?
      .check-group
        = ep.input :doing_good_inspiring,       :label => ( link_to "Inspiring",                 '/high-impact-careers#inspiring-others', :target => '_blank' )
        = ep.input :doing_good_improving,       :label => ( link_to "Improving",                 '/high-impact-careers#improving',        :target => '_blank' )
        = ep.input :doing_good_philanthropy,    :label => ( link_to "Philanthropy",              '/high-impact-careers#philanthropy',     :target => '_blank' )
        = ep.input :doing_good_prophilanthropy, :label => ( link_to "Professional philanthropy", '/high-impact-careers#philanthropy',     :target => '_blank' )
        = ep.input :doing_good_innovating,      :label => ( link_to "Innovating",                '/high-impact-careers#innovating',       :target => '_blank' )
        = ep.input :doing_good_research,        :label => ( link_to "Research",                  '/high-impact-careers#research',         :target => '_blank' )
      
        %hr
      %label
        Which causes do you intend to donate to?
      .check-group
        = ep.input :causes_givewell,      :label => "GiveWell recommended charities"
        = ep.input :causes_gwwc,          :label => "GWWC recommended charities"
        = ep.input :causes_political,     :label => "Political charities"
        = ep.input :causes_animal,        :label => "Animal charities"
        = ep.input :causes_xrisk,         :label => "X-risk charities"
        = ep.input :causes_meta,          :label => "Meta-philanthropy charities"
        = ep.input :causes_domestic,      :label => "Other domestic charities"
        = ep.input :causes_international, :label => "Other international charities"
      = f.input :causes_comment, :placeholder => "optional", :label => "Comments about causes", :required => false, :input_html => {:rows=>'5'}
 

  %hr

  = field_set_tag "Private profile fields: only visible to other 80,000 Hours members" do
    = ep.input :skills_knowledge_share,
               label: "What skills and knowledge would you be willing to share with other 80k members?",
               placeholder: "this will not be publicy visible",
               input_html: { rows: '10' } 

    = ep.input :skills_knowledge_learn,
               label: "What skills and knowledge would you like to gain from other 80k members?",
               placeholder: "this will not be publicy visible",
               input_html: { rows: '10' } 

  %hr
  .center
    = f.button :submit, "Save profile", class: 'btn btn-success btn-large'
    = link_to "Cancel", user_path(current_user), class: 'btn btn-large'

    - if @etkh_profile.errors.any?
      .alert.alert-error
        <a class="close" data-dismiss="alert">×</a>
        %h4.alert-heading 
          = pluralize(@etkh_profile.errors.count, "error")
          prohibited this application from being accepted!
        %ul
          - @etkh_profile.errors.reverse_each do |field,msg|
            -# only want to print field if coming from Devise (password, or email).
            -# otherwise we print our custom error messges as defined in models user
            %li
              = (field == :password || field == :email) ? field.to_s.humanize : '' 
              = msg
    
      .slider-container
        %label
          How much do you expect to donate to the highest impact causes?
        .slider-group
          %p
            %strong
              I intend to donate around <span class="slider_value emphasise"><span id="etkh_profile_donation_percentage_display"></span>%</span> of my pre-tax income each year.
    
        .slider#etkh_profile_donation_percentage_slider
          = f.input :donation_percentage, :as => :hidden
      %br
      = f.input :donation_percentage_comment, :placeholder => "optional", :label => "Comments about donations", :required => false, :input_html => {:rows=>'5'}
    
      %hr

app/views/etkh_profiles/_disabled_warning.html.haml
.disabled-warning
  - if !current_user
    .page-header
      %h3 Step 1: You need to create an account!
    .alert.alert-error
      %p
        Before you can fill in the membership form, you need to be signed in to an 80000hours.org account. You can sign in if you have an existing account, or quickly create a new account, then return here and fill in the membership form.
      .center
        #{link_to "sign in", new_user_session_path, :class => 'btn'} or #{link_to "create an account", new_user_registration_path, :class=> 'btn'}
  - elsif current_user.etkh_profile
    .alert.alert-error
      %h3.alert-heading You're already an 80,000 Hours member!
      Please contact #{link_to 'join@80000hours.org', 'mailto:join@80000hours.org'} if you have any questions.

app/views/etkh_profiles/_form.html.haml
= javascript_include_tag "application-form.js"
= simple_form_for(current_user, url: user_etkh_profile_url(current_user, current_user.etkh_profile),
                                html: { class: 'form-horizontal' },
                                defaults: { input_html: { class: 'span4' } }  ) do |f|

  = f.label "Add a photo to your profile"
  - if current_user.avatar?
    = link_to image_tag(current_user.avatar.url(:small), :class=>"shadow", :style=>"margin-left:20px;"), current_user.avatar.url
  - else
    = image_tag("profiles/avatar_default_96x96.png", :class=>"shadow")
  = f.input :avatar, :label => "Change photo"

  %hr

  = f.fields_for :etkh_profile, defaults: { input_html: { class: 'span4' } } do |ep|
    %h2 A bit about you
    = f.input :location,
              placeholder: "e.g. Oxford, England"

    = ep.input :organisation,
               label: "Organisations you belong to",
               placeholder: "e.g. Fake College, MegaCorp"

    = ep.input :background,
               label: "Tell the other members of 80,000 Hours a little about yourself. What are you career plans, and how have they changed? What do you currently do? Why did you join 80,000 Hours?"

    %hr

    %h2 Knowledge sharing

    = ep.input :skills_knowledge_share,
               label: "What skills and knowledge would you be willing to share with other 80k members?",
               placeholder: "this will only be visible to 80,000 Hours members",
               input_html: { rows: '10' } 

    = ep.input :skills_knowledge_learn,
               label: "What skills and knowledge would you like to gain from other 80k members?",
               placeholder: "this will only be visible to 80,000 Hours members",
               input_html: { rows: '10' } 
    %hr
               
    %h2 Declare your intention to give 
    %p
    Many of our members make a declaration of their intent to give a certain
    percentage of their pre-tax income to cost-effective causes over their
    lifetime. They find this helps them to stay true to their aims to give money
    and encourages others to do the same.

    = f.fields_for :etkh_profile, defaults: { input_html: { class: 'span4' } } do |ep|
      I intend to donate around <span class="slider_value emphasise"><span id="user_etkh_profile_attributes_donation_percentage_display"></span>%</span> of my pre-tax income each year.
      .slider#user_etkh_profile_attributes_donation_percentage_slider
    = ep.input :donation_percentage, :as => :hidden
    = ep.input :donation_percentage_optout, label: "I don't want to make a declaration"

  %hr
  = f.fields_for :etkh_profile do |ep|

    = ep.association :profile_option_causes,
                     :as => :check_boxes,
                     :label => "Given what you know now, which causes do you think you are most likely to promote, give money to and work within in order to help others?"
    = ep.input :causes_comment,
               label: "Comments about causes",
               input_html: {rows: '2', class: 'span4'}

    = ep.association :profile_option_activities,
                     :as => :check_boxes,
                     :label => "Which high impact activities do you intend to get involved in?"
    = ep.input :activities_comment, 
               label: "Comments about high impact activities",
               input_html: {rows: '2', class: 'span4'}

    %hr


  %h2 External websites

  = f.input :external_website,   label: "Personal website", placeholder: "e.g. http://www.joebloggs.com/"
  = f.input :external_twitter,   label: "Twitter page",     placeholder: "e.g. http://twitter.com/JoeBloggs"
  = f.input :external_facebook,  label: "Facebook page",    placeholder: "e.g. http://www.facebook.com/JoeBloggs"
  = f.input :external_linkedin,  label: "LinkedIn page",    placeholder: "e.g. http://www.linkedin.com/in/JoeBloggs"


  = f.fields_for :etkh_profile, defaults: { input_html: { class: 'span4' } } do |ep|
    %hr
    %h2 Privacy
    = ep.input :public_profile,
               label: "Public profile",
               hint: "if unchecked your profile is still visible to 80,000 Hours members"

  %hr
  .center
    = f.button :submit, "Save profile", class: 'btn btn-success btn-large'
    = link_to "Cancel", user_path(current_user), class: 'btn btn-large'

app/views/etkh_profiles/_latest_profiles.html.haml
%h3= link_to 'Latest profiles', etkh_profiles_path
- @latest_profiles.each do |profile|
  .sidebar-item
    = image_tag profile.user.avatar(:thumb), class: 'avatar'
    = link_to profile.user.name, etkh_profile_path(profile.user)
    %span.date= profile.created_at.strftime("%B %d, %Y")

app/views/etkh_profiles/_profile.html.haml
- user = profile.user

.row
  .eighty-thousand-hours-profile
    .span3
      .sidebar
        .avatar
          = link_to image_tag(user.avatar.url(:medium)), user.avatar.url

        - if user.location?
          %p
            %h5 Location
            = user.location

        %p
          %h5 Member since 
          = profile.created_at.strftime "%B %Y"

        - upvotes = user.votes.upvotes.recent
        - if upvotes.size > 0
          %p
            %h5 Recent activity
            - user.blog_posts.published.limit(3).each do |post|
              wrote blog post:
              %br
              =link_to post.title, post
              %br
            - upvotes.limit(3).each do |v|
              - if !v.blog_post.nil?
                liked blog post:
                %br
                =link_to v.blog_post.title, blog_post_path(v.blog_post)
                %br

        -if user.external_links?
          %p
            %h5 External links
            - if user.external_website?
              = link_to "<i class='icon-info-sign'></i> Personal website".html_safe, user.external_website
              %br

            - if user.external_twitter?
              = link_to image_tag("social/twitter.png") + " Twitter".html_safe, user.external_twitter
              %br
            
            - if user.external_facebook?
              = link_to image_tag("social/facebook.png") + " Facebook".html_safe, user.external_facebook
              %br
            
            - if user.external_linkedin?
              = link_to image_tag("social/linkedin.png") + " LinkedIn".html_safe, user.external_linkedin
              %br

        %p
          %h5 Navigation
          = link_to '<i class="icon-user"></i> view all members'.html_safe, etkh_profiles_path
    .span1
      &nbsp;
    .span8
      .main
        .page-header
          %h1= profile.name
          %h2.location
            - if profile.organisation?
              = profile.organisation + (', ' if user.location)
            - if user.location?
              = user.location
        
        - if profile.background?
          %h2 Background and interests
          = markdown profile.background

        - if profile.profile_option_causes.any?
          %h2 Causes I support
          %ul
            - profile.profile_option_causes.each do |cause|
              %li= cause.title
          - if profile.causes_comment
            = markdown profile.causes_comment

        - if profile.profile_option_activities.any?
          %h2 My high impact activities
          %ul
            - profile.profile_option_activities.each do |activity|
              %li= activity.title
          - if profile.activities_comment
            = markdown profile.activities_comment

        - if !profile.donation_percentage_optout
          %h2 Donation pledge
          .donations-thermometer.well
            .text
              %p 
                I have pledged to donate #{profile.donation_percentage}% of my pre-tax income to cost-effective causes.
            .bar-container
              .progress.progress-striped.progress-danger
                .bar{:"data-percentage" => profile.donation_percentage}

        // only show skills to other members
        - if current_user and current_user.eighty_thousand_hours_member?
          - if profile.skills_knowledge_share?
            %h2 Skills and knowledge I can share with other members
            %p= profile.skills_knowledge_share
          - if profile.skills_knowledge_learn?
            %h2 Skills and knowledge I would like to learn from other members
            %p= profile.skills_knowledge_learn
        
        // only show donations to members
        - if current_user and current_user.eighty_thousand_hours_member?
          - donations = user.donations.order("date DESC")
          - if donations.confirmed.is_public.size > 0
            .donations{:id => "#{user.slug}-donations"}
              %h2
                Donations
              %p
                %ul
                  - donations.each do |donation|
                    - if donation.public
                      %li
                        = render donation

        - if user.blog_posts.published.size > 0
          .blog
            %h2 Recent blog posts
            - user.blog_posts.published.limit(3).each do |post|
              =render :partial => 'blog_posts/display_heading', :locals => {:post => post}

app/views/etkh_profiles/_profile_condensed.html.haml
- user = profile.user

.eighty-thousand-hours-profile-condensed
  .avatar
    = link_to image_tag(user.avatar.url(:thumb)), "/members/#{user.slug}"

  .text
    %span.name
      = link_to user.name, "/members/#{user.slug}"
    %br
    - if user.location?
      %span.location
        = truncate( user.location, :length => 20 )

app/views/etkh_profiles/_search_form.html.haml
= form_tag('/members/search', :class => 'form-horizontal') do
  .control-group
    %label.control-label{ for: 'prependedInput'}
      Search by name
    .controls
      .input-prepend
        = '<span class="add-on"><i class="icon-search"></i></span>'.html_safe + (text_field_tag 'name', '', :placeholder => 'search by name', :id => 'prependedInput', :"data-provide"=>"typeahead", :"data-source"=>"#{@profiles.map{|p| p.user.name}}").html_safe

app/views/etkh_profiles/edit.html.haml
.row
  .span12
    .row
      .span7
        .box
          %h1= current_user.name
          :markdown
            ##You can now:
            ###[Ask a question on our discussion forum](/discussion)
            Get career advice or just find out more about 80,000 Hours. People are happy to help you out. [Ask a question here](/discussion)
            
            ###[Help us out](https://docs.google.com/spreadsheet/viewform?formkey=dG5PbFBRZFk4OXNSb0hGTUc2T08yNUE6MQ#gid=0):
            Help us to evaluate our impact by filling in the [members' survey](https://docs.google.com/spreadsheet/viewform?formkey=dG5PbFBRZFk4OXNSb0hGTUc2T08yNUE6MQ#gid=0) so that we can continue to offer free advice.
          %h2 Fill in your profile
          = render 'form'
      .span1
        &nbsp;
          
      .span4
        .box.sidebar
          %h2 Public profile
          %p
            By creating a public profile, you can help inspire new people to join 80k.
            Seeing example members is a really effective way to persuade others to join.
            You can also make yourself known to our community, which might lead to
            connections with other effective altruists.

          %h2 Markdown
          %p All the text fields can be formatted using the <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>. For example:
          %p **bold text** == <strong>bold text</strong>
          %p _italic text_ == <em>italic text</em>
          %p [a link](http://80000hours.org/) == <a href="http://80000hours.org">a link</a>

app/views/etkh_profiles/index.html.haml
.box
  .page-header
    %h1= "#{@profiles.size} member profiles"
  
  = render :partial => 'search_form'
  
  Jump to:&nbsp;
  - @grouped_profiles.each do |letter,profiles|
    =link_to letter, "##{letter}"
    &nbsp;|&nbsp;
  
  .page-header
    %h3 Newest members

  - @newest_profiles.in_groups_of(4) do |profiles|
    .row
      - profiles.each do |profile|
        .span3
          = render :partial => 'profile_condensed', :locals => { :profile => profile }
      .clearfix
  %hr

  - @grouped_profiles.to_a.in_groups_of(4) do |groups|
    .row
      - groups.each do |profiles|
        - if profiles
          .span3
            .page-header{:id => profiles[0]}
              %h1= profiles[0]
            - profiles[1].each do |profile|
              = render :partial => 'profile_condensed', :locals => { :profile => profile }
              .clearfix
              %br
.clearfix

app/views/etkh_profiles/new.html.haml
.row
  .span12
    .row
      .span7
        .box
          %h1= current_user.name
          :markdown
            ##You can now:
            ###[Ask a question on our discussion forum](/discussion)
            Get career advice or just find out more about 80,000 Hours. People are happy to help you out. [Ask a question here](/discussion)
            
            ###[Help us out](https://docs.google.com/spreadsheet/viewform?formkey=dG5PbFBRZFk4OXNSb0hGTUc2T08yNUE6MQ#gid=0):
            Help us to evaluate our impact by filling in the [members' survey](https://docs.google.com/spreadsheet/viewform?formkey=dG5PbFBRZFk4OXNSb0hGTUc2T08yNUE6MQ#gid=0) so that we can continue to offer free advice.
          %h2 Fill in your profile
          = render 'form'
      .span1
        &nbsp;
          
      .span4
        .box.sidebar
          %h2 Public profile
          %p
            By creating a public profile, you can help inspire new people to join 80k.
            Seeing example members is a really effective way to persuade others to join.
            You can also make yourself known to our community, which might lead to
            connections with other effective altruists.

          %h2 Markdown
          %p All the text fields can be formatted using the <a href="http://daringfireball.net/projects/markdown/syntax">Markdown syntax</a>. For example:
          %p **bold text** == <strong>bold text</strong>
          %p _italic text_ == <em>italic text</em>
          %p [a link](http://80000hours.org/) == <a href="http://80000hours.org">a link</a>

app/views/etkh_profiles/show.html.haml
= render :partial => 'profile', :locals => { :profile => @profile }

.box
  .center
    = link_to '<i class="icon-user"></i> back to member list'.html_safe, etkh_profiles_path