config/routes.rb
EightyThousandHours::Application.routes.draw do
  resources :authentications do
    get 'create_new_account', :on => :collection
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts',
                     :controllers => { :sessions => 'sessions',
                                       :registrations => 'registrations' }

  match '/accounts/merge' => 'users#merge'

  match '/blog/feed.atom' => 'blog_posts#feed', :as => :feed, :defaults => { :format => 'atom' }
  resources :blog_posts, :path => 'blog' do
    collection do
      get 'drafts'
      get :tag
      get :author
      get :vote
    end
  end

  resources :discussion_posts, :path => 'discussion' do
    collection do
      get 'drafts'
    end
  end

  resources :comments

  resources :causes, :only => [:new,:create,:show,:index], :path => 'donations/causes'
  resources :donations, :only => [:new,:create,:update,:show,:index,:edit]

  resources :votes, :only => [:new,:create,:delete]

  resources :supporters, :only => [:new, :create], :path => 'show-your-support'
  match 'show-your-support' => 'supporters#new'

  resources :chat_requests, :only => [:new,:create], :path => 'chat-to-us'
  match 'chat-to-us' => 'chat_requests#new'

  resources :career_advice_requests, :only => [:new,:create], :path => 'request-a-career-advice-session'
  match 'request-a-career-advice-session' => 'career_advice_requests#new'

  resources :endorsements, :only =>[:index]
  resources :videos, :only =>[:index]

  resources :etkh_profiles, :path => "members", :only => [:new,:create,:show,:index] do
    collection do
      post 'search'
    end
  end

  resources :users, :path => 'accounts', :only => [:show,:edit,:update,:destroy] do
    resources :etkh_profiles 
    member do
      get 'posts'
    end
    collection do
      get 'all'
      get 'email_list'
    end
  end

  resources :surveys, :only => [:show]

  # pages which don't live in the database as they can't be
  # converted to pure Markdown
  match 'events'             => 'info#events'
  match 'events/past-events' => 'info#past_events'
 
  # pages from old HIC site
  match 'ethical-career'                => 'info#banker_vs_aid_worker'
  match 'old-ethical-career'            => 'info#ethical_career'
  match 'what-you-can-do'               => 'info#what_you_can_do'
  match 'what-you-can-do/my-donations'  => 'info#my_donations'
  match 'what-we-do'                    => 'info#what_we_do'

  # all other pages are stored as Markdown in the database
  root :to => 'pages#show', :id => "home"
  match 'search'        => 'pages#search'
  match 'mailing-list'  => 'pages#mailing_list'
  match 'sitemap'       => 'pages#sitemap'
  match 'survey_test'   => 'pages#survey_test'
  resources :pages
  resources :pages, :path => '/', :only => [:show]
end

app/views/shared/_cause_donation_member_sidebar.html.haml
%ul.nav.nav-pills.nav-stacked
  %li
    = link_to 'Causes', causes_path
  %li
    = link_to 'Donations', donations_path
  %li
    = link_to 'Members', etkh_profiles_path

app/views/shared/_charity_donation_member_sidebar.html.haml
%p
  %h2 Navigation
%p
  = link_to 'Charities', charities_path
%p
  = link_to 'Donations', donations_path
%p
  = link_to '80,000 Hours members', users_path

app/views/shared/_declaration.html.erb
<%= markdown "
###I declare that I aim to pursue a career as an effective altruist.

This means that I intend to:

1. Devote a significant proportion of my time or resources to helping others.
2. Use the time or resources I give as effectively as possible in helping others.
3. Make my career decisions based at least in part on how it enables me to further my altruistic aims.
" %>

app/views/shared/_google_analytics.html.erb
  <!-- Google analytics -->
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-27180853-1']);
    _gaq.push(['_trackPageview']);
  
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

app/views/shared/_header_endorsement.html.haml
- endorsement = Endorsement.get_header_endorsement
- if endorsement
  .endorsement
    %a{:href => '/endorsements'}
      .endorsement-body
        = markdown ('"' + endorsement.body + '"')
      .attribution
        %span.author
          = endorsement.author
        &nbsp;
        = endorsement.position

app/views/shared/_home.html.erb
<div class="span12">
  <div class="row">
    <div class="span12">
      <a class="fp-splash-find-out-more btn btn-primary btn-large" href="/find-out-more">Find out more &gt;</a>
      <div class="fp-splash">
        <h1>Careers that make a real difference.</h1>
        <h3>Discover how to change the world through your career.</h3>
        <h3>Eighty thousand hours to make an impact. Start here.</h3>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mailing_list.html.erb
<!-- Begin MailChimp Signup Form -->
<span class="mailing-list-form <%= klass %>">
<form action="http://eightythousand.us2.list-manage.com/subscribe/post?u=aba12f58bbe8075560abdc5b7&id=43bc1ae55c&group[12541][1]=true" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank">
  <label for="mce-EMAIL"><%= text %></label>
  <input type="email" name="EMAIL" class="defaultText email" title="email@address.com" id="mce-EMAIL" />
  <input type="submit" value="<%= defined?(button_text) ? button_text : "Subscribe" %>" name="subscribe" id="mc-embedded-subscribe" class="btn btn-small" />
</form>
</span>
<!--End mc_embed_signup-->

app/views/shared/_member.html.haml
.member-profile
  - if user_signed_in? && current_user.member == member
    .center
      = link_to "Edit Your Profile", "/accounts/edit", :class=>"btn btn-success"
      %hr

  - if profile.name
    .page-header
      - if member.avatar?
        .avatar
          = link_to image_tag(member.avatar.url(:medium)), member.avatar.url
      %h1= profile.name
      - if member.location?
        %h2.location= member.location

  
  .donations
    %p
      = member_donations member.donations.sum(:amount)
  
  %h2 Joined 80,000 Hours
  = profile.created_at.strftime "%B %Y"

  %hr

  - if profile.organisation?
    %h2 Organisation/Company/University
    = markdown profile.organisation
    %hr

  - if profile.background?
    %h2 Background and interests
    = markdown profile.background
    %hr
  
  - if profile.inspiration?
    %h2 My inspiration for joining 80,000 Hours
    = markdown profile.inspiration
    %hr

  - if profile.occupation?
    %h2 Current job/occupation
    = markdown profile.occupation
    %hr

  - if profile.career_plans?
    %h2 Career plans
    = markdown profile.career_plans
    %hr

  - if profile.doing_good_inspiring? || profile.doing_good_research? || profile.doing_good_philanthropy? || profile.doing_good_prophilanthropy? || profile.doing_good_innovating? || profile.doing_good_improving
    %h2 Type of Career
    %ul 
      - if profile.doing_good_inspiring?
        %li Inspiring others
      - if profile.doing_good_research?
        %li High impact research
      - if profile.doing_good_philanthropy?
        %li Philanthropy
      - if profile.doing_good_prophilanthropy?
        %li Professional philanthropy
      - if profile.doing_good_innovating?
        %li Innovating
      - if profile.doing_good_improving?
        %li Improving
    %hr

  - if profile.organisation_role?
    %h2 Role in 80,000 Hours
    = markdown profile.organisation_role
    %hr

  - if profile.interesting_fact?
    %h2 Interesting fact
    = markdown profile.interesting_fact
    %hr

  - if member.external_twitter? || member.external_facebook? || member.external_linkedin?
    %h2 External links
    - if member.external_twitter?
      = link_to image_tag("social/twitter.png") + " Twitter".html_safe, member.external_twitter

    - if member.external_facebook?
      = link_to image_tag("social/facebook.png") + " Facebook".html_safe, member.external_facebook

    - if member.external_linkedin?
      = link_to image_tag("social/linkedin.png") + " LinkedIn".html_safe, member.external_linkedin

app/views/shared/_opengraph.html.erb
    <!-- for facebook open graph -->
    <meta property="og:title" content="<%= page_title(false) %>"/>
    <% if @og_type %>
      <meta property="og:type" content="<%= @og_type %>"/>
    <% else %>
      <meta property="og:type" content="non_profit"/>
    <% end %>
    <meta property="og:url" content="<%= request.url %>"/>
    <!--<meta property="og:image" content="http://80000hours.org/assets/opengraph/logo.png"/>-->
    <meta property="og:site_name" content="80,000 Hours" />
    <meta property="fb:admins" content="36804805"/>
    <% if @og_desc %>
      <meta property="og:description" content="<%= strip_tags(strip_links(sanitize(markdown @og_desc))) %>"/>
    <% else %>
      <meta property="og:description" content="80,000 Hours is an organisation which supports and guides people who are pursuing careers which will allow them to do the most good in the world."/>
    <% end %>

app/views/shared/_pledge.html.erb
<%= markdown "
I pledge that, over my lifetime, I will dedicate **10% of my income or working
time**, or any combination of the two, to those **causes that I believe will do
the most good** with the resources I give them. I understand that it is
difficult to know the best way of doing good in the world, and so I will choose
those cause(s) on the basis of the **best evidence** that is available to me at
the time. Further, I will deliberately **pursue a career that will enhance my
ability to further those causes** I believe to be best.
" %>

app/views/shared/_show_donation.html.haml
- if donation.user == current_user
  = link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_donation_path(donation), :class => 'edit'

- if donation.public?
  = link_to donation.user.name, etkh_profile_path(donation.user)
- else
  = "An anonymous member"

donated

- if donation.public_amount?
  %strong
    = donation.with_currency

to
= link_to donation.cause.name, cause_path(donation.cause)

on
- date = (donation.date ? donation.date : donation.created_at)
= date.strftime('%d %B, %Y')

app/views/shared/_sidebar_item.html.haml
.sidebar-item
  - if defined? content
    .content= content
  .attribution
    - if defined? attribution
      = "by ".html_safe + attribution
  -# Commented out dates to remove clutter    
  -# - if defined? date
  -#    on
  -#    %span.date= format_date(date)

app/views/shared/_social_media.html.erb
<a class='social-btn-facebook-light' href='http://www.facebook.com/80000Hours'>Facebook</a>
<a class='social-btn-twitter-light' href='http://www.twitter.com/80000Hours'>Twitter</a>
<a class='social-btn-reddit-light' href='http://reddit.com/r/EffectiveAltruism'>Reddit</a>
<a class='social-btn-rss-light' href='/blog/feed.atom'>RSS</a>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=371972292815616";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div class="fb-like" data-href="http://www.facebook.com/80000Hours" data-colorscheme="dark" data-send="true" data-width="430" data-show-faces="false"></div>

app/views/shared/_user_nav.html.haml
.container.navbar-container
  .row
    .span12
      .navbar.navbar-top.navbar-inverse
        .navbar-inner
          / .btn-navbar is used as the toggle for collapsed navbar content
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .nav-collapse
            %ul.nav.pull-right
              - if user_signed_in?
                %li.dropdown
                  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                    %span.username= current_user.name
                    %b.caret
                  %ul.dropdown-menu
                    %li= link_to "Account settings", edit_user_registration_path
                    - if current_user.eighty_thousand_hours_member?
                      %li= link_to "Edit profile", edit_user_etkh_profile_path(current_user, current_user.etkh_profile)
                      %li= link_to "View profile", etkh_profile_path(current_user)
                      %li= link_to "Donations", donations_path
                    - if can? :access, :admin
                      %li= link_to "Admin", admin_dashboard_path
                    %li.divider
                    %li= link_to "Logout", destroy_user_session_path
              - else
                %li= link_to "Login", new_user_session_path
                %li= link_to "Signup", '/join'