config/routes.rb
EightyThousandHours::Application.routes.draw do
  resources :authentications do
    get 'create_new_account', :on => :collection
  end

  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#failure'

  ActiveAdmin.routes(self)

  devise_for :users, :path => 'accounts',
                     :controllers => { :sessions => 'sessions',
                                       :registrations => 'registrations' }

  match '/accounts/merge' => 'users#merge'

  match '/blog/feed.atom' => 'blog_posts#feed', :as => :feed, :defaults => { :format => 'atom' }
  resources :blog_posts, :path => 'blog' do
    collection do
      get 'drafts'
      get :tag
      get :author
      get :vote
    end
  end

  resources :discussion_posts, :path => 'discussion' do
    collection do
      get 'drafts'
    end
  end

  resources :comments

  resources :causes, :only => [:new,:create,:show,:index], :path => 'donations/causes'
  resources :donations, :only => [:new,:create,:update,:show,:index,:edit]

  resources :votes, :only => [:new,:create,:delete]

  resources :supporters, :only => [:new, :create], :path => 'show-your-support'
  match 'show-your-support' => 'supporters#new'

  resources :chat_requests, :only => [:new,:create], :path => 'chat-to-us'
  match 'chat-to-us' => 'chat_requests#new'

  resources :career_advice_requests, :only => [:new,:create], :path => 'request-a-career-advice-session'
  match 'request-a-career-advice-session' => 'career_advice_requests#new'

  resources :endorsements, :only =>[:index]
  resources :videos, :only =>[:index]

  resources :etkh_profiles, :path => "members", :only => [:new,:create,:show,:index] do
    collection do
      post 'search'
    end
  end

  resources :users, :path => 'accounts', :only => [:show,:edit,:update,:destroy] do
    resources :etkh_profiles 
    member do
      get 'posts'
    end
    collection do
      get 'all'
      get 'email_list'
    end
  end

  resources :surveys, :only => [:show]

  # pages which don't live in the database as they can't be
  # converted to pure Markdown
  match 'events'             => 'info#events'
  match 'events/past-events' => 'info#past_events'
 
  # pages from old HIC site
  match 'ethical-career'                => 'info#banker_vs_aid_worker'
  match 'old-ethical-career'            => 'info#ethical_career'
  match 'what-you-can-do'               => 'info#what_you_can_do'
  match 'what-you-can-do/my-donations'  => 'info#my_donations'
  match 'what-we-do'                    => 'info#what_we_do'

  # all other pages are stored as Markdown in the database
  root :to => 'pages#show', :id => "home"
  match 'search'        => 'pages#search'
  match 'mailing-list'  => 'pages#mailing_list'
  match 'sitemap'       => 'pages#sitemap'
  match 'survey_test'   => 'pages#survey_test'
  resources :pages
  resources :pages, :path => '/', :only => [:show]
end

app/models/donation.rb
class Donation < ActiveRecord::Base
  before_save :ensure_date_filled

  validates :user_id, presence: true
  validates :cause_id, presence: true
  validates :amount_cents, numericality: { greater_than_or_equal_to: 1 }
  validates :currency, :inclusion => { :in => %w(GBP USD EUR),
            :message => "Currency must be GBP, USD, or EUR (%{value} given)" }

  monetize :amount_cents

  belongs_to :cause
  belongs_to :user

  after_create :send_confirmation_email_to_user

  attr_accessible :user_id,
                  :cause_id,
                  :amount,
                  :amount_cents,
                  :receipt,
                  :public,
                  :public_amount,
                  :date,
                  :currency,
                  :confirmed
  
  # paperclip gem for receipt uploads to s3
  has_attached_file :receipt,
                    :storage => :s3, 
                    :s3_credentials => { :access_key_id     => ENV['S3_ACCESS'],
                                         :secret_access_key => ENV['S3_SECRET'],
                                         :bucket            => ENV['S3_BUCKET'] },
                    :path => "/donations/:id/:filename"

  scope :confirmed, where(:confirmed => true).order("date DESC")
  scope :is_public, where(:public => true)
  scope :is_public_amount, is_public.where(:public_amount => true)

  def self.total( currency = "GBP", with_symbol = false )
    donations = Donation.confirmed.all
    if donations.any?
      total = Donation.confirmed.all.map{|d| d.amount.exchange_to(currency).dollars}.sum
      if with_symbol
        "#{ActionController::Base.helpers.number_to_currency(total, unit: "&pound;", precision: 0)}"
      else
        sprintf '%.0f', total
      end
    end
  end

  def self.target
    "&pound;80,000".html_safe
  end

  def self.target_percentage
    (100 * Donation.total(:GBP,false).to_f / 80000.0).to_i
  end

  def confirm!
    self.confirmed = true
    self.save
    send_acceptance_email_to_user
  end

  def with_currency
    "#{amount.currency.symbol}#{ "%g" % amount.dollars }"
  end

  def with_currency_word
    "#{amount.currency.iso_code} #{ "%g" % amount.dollars }"
  end

  private
    def send_confirmation_email_to_user
      if self.confirmed
        send_acceptance_email_to_user
      else
        DonationMailer.confirmation(self).deliver!
      end
    end
    def send_acceptance_email_to_user
      DonationMailer.accepted(self).deliver!
    end

    def ensure_date_filled
      if self.date.blank?
        self.date = DateTime.now
      end
    end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  load_and_authorize_resource

  def index
    @donations = Donation.confirmed
    @your_donations = current_user.donations if current_user
  end

  def create
    @donation = Donation.new(params[:donation])
    @donation.currency = params[:donation][:currency]

    if !@donation.user_id
      @donation.user_id = current_user.id
    end

    if @donation.save
      flash[:"alert-success"] = "Thanks #{current_user.first_name}, your donation is being processed! We'll send you an email once it's been added to your profile."
      redirect_to donations_path
    else
      render :new
    end
  end

  def new
    @donation = Donation.new( :user => current_user )
    authorize! :create, Donation, :message => "You need to <a href='/accounts/sign_in'>sign in</a> or <a href='/join'>sign up</a> to make a donation!".html_safe
  end

  def edit
    @donation = current_user.donations.find( params[:id] )
    authorize! :edit, Donation, :message => "You need to <a href='/accounts/sign_in'>sign in</a> or <a href='/join'>sign up</a> to edit a donation!".html_safe
  end

  def show
    @donation = Donation.find(params[:id])
  end

  def update
    @donation = current_user.donations.find(params[:id])
    if @donation.update_attributes(params[:donation])
      flash[:"alert-success"] = "Your donation details were updated successfully"
      redirect_to(@donation)
    else
      render :action => "edit"
    end
  end
end

app/views/donations/_donation.html.haml
- if donation.user == current_user
  = link_to '(edit)'.html_safe, edit_donation_path(donation), :class => 'edit'

%span.attribution
  - if donation.public?
    = link_to donation.user.name, etkh_profile_path(donation.user)
  - else
    = "An anonymous member"

donated

- if donation.public_amount?
  %strong
    = donation.with_currency

to
= link_to donation.cause.name, cause_path(donation.cause)

on
- date = (donation.date ? donation.date : donation.created_at)
%span.date= format_date(date)

app/views/donations/_form.html.haml
- if @donation.errors.any?
  .alert.alert-error
    <a class="close" data-dismiss="alert">×</a>
    %h4.alert-heading 
      = pluralize(@donation.errors.count, "error")
      prohibited this donation from being processed!
    %ul
      - @donation.errors.reverse_each do |field,msg|
        %li
          = msg

= simple_form_for @donation, :html => {:class => 'form-horizontal'} do |f|
  = field_set_tag 'Donation details' do
    - if( page == :edit )
      = f.association :cause, :disabled => true, :required => false
      = f.input :currency, :disabled => true
      = f.input :currency, :disabled => true, :collection => ['GBP','USD','EUR'], :as => :radio_buttons, :input_html => {:style => 'text-align: left'}
      = f.input :amount, :disabled => true
    - else
      = f.association :cause, :required => true,
                      :hint => "cause not listed? #{link_to "add it here", new_cause_path }".html_safe
      = f.input :currency, :collection => ['GBP','USD','EUR'], :as => :radio_buttons, :input_html => {:style => 'text-align: left'}, :checked => 'GBP'
      = f.input :amount, :required => true
    = f.input :date, :as => :string, :placeholder => 'yyyy-mm-dd', :hint => 'only add donations made after you joined 80,000 Hours', :required => true, :input_html => { id: 'datepicker' }
  = field_set_tag "#{ (page == :new ) ? 'Accountability' : 'Privacy' }" do
    - if( page == :new )
      = f.input :receipt, :hint => "PDF donation receipt from cause"
      %p
        %strong Note:
        Instead of uploading a receipt, you can submit this form and then
        forward a donation receipt to 
        = link_to 'donations@80000hours.org', 'mailto:donations@80000hours.org'
        Please include your name in the email subject line.
    = f.input :public, :label => 'Display donation publicly?'
    = f.input :public_amount, :label => 'Make amount donated public?'
  %hr
  .center
    = f.button :submit, "Submit donation",
               :class=> "btn form btn-large btn-primary",
               :"data-loading-text" => "Submitting... please wait"

app/views/donations/_latest_donations.html.haml
%h3= link_to 'Latest donations', donations_path
- @latest_donations.each do |donation|
  = render partial: 'shared/sidebar_item',
           locals: { content: render( donation ) }

app/views/donations/_thermometer.html.haml
.donations-thermometer.well
  .text
    %p 
      Our members have #{link_to 'donated', donations_path} 
      %strong= Donation.total(:GBP,true).html_safe
      to the #{link_to 'best causes', causes_path}.
    %p The next milestone: #{Donation.target} by the end of 2012.
  .bar-container
    .target= Donation.target
    .progress.progress-striped.progress-danger
      .bar{:"data-percentage" => Donation.target_percentage}

app/views/donations/edit.html.haml
.row
  .span2
    .box.sidebar
      = render :partial => "shared/cause_donation_member_sidebar"

  .span10
    .box.left-border
      .page-header
        %h1 Edit a donation
      %p
        You can change the privacy settings of your donation using the form below.

      = render :partial => 'form', :locals => { :page => :edit }

app/views/donations/index.html.haml
.row
  .span2
    .box.sidebar
      = render :partial => "shared/cause_donation_member_sidebar"

  .span10
    .box.left-border
      .page-header
        %h1 Donations


      %p
        If you're an 80,000 Hours member and would like your charitable donations to be associated with
        your account, then please follow the steps:
        %ol
          %li Make a donation to a cause through <strong>their website</strong>
          %li Click the button below to <strong>submit your donation receipt to us</strong>
      
        = link_to 'Submit donation', new_donation_path, :class => 'btn'
      
      %hr
      - if @your_donations
        %h2 Your donations
        %p
          %ul
            - @your_donations.each do |donation|
              %li
                = render donation
        %hr

      = render 'donations/thermometer'

      %hr

      %h2 Here are some recent donations
      - if @donations
        %p
          %ul
            - @donations.each do |donation|
              %li
                = render donation

app/views/donations/new.html.haml
.row
  .span2
    .box.sidebar
      = render :partial => "shared/cause_donation_member_sidebar"

  .span10
    .box.left-border
      .page-header
        %h1 Make a donation
      %p
        Add details of a donation to your 80,000 Hours profile by using the form below.
      %p
        For accountability we need you to upload a PDF donation receipt, or to forward an email receipt to us.
      %p
        %strong Note:
        Please only add donations which you made after joining 80,000 Hours!

      = render :partial => 'form', :locals => { :page => :new }

app/views/donations/show.html.haml
.row
  .span2
    .box.sidebar
      = render :partial => "shared/cause_donation_member_sidebar"

  .span10
    .box.left-border
      .page-header
        %h1 Donation to #{@donation.cause.name}
      %p
        = render @donation

      - if current_user && current_user == @donation.user
        %hr
        %h2 This is your donation
        %p
          You can change the privacy settings of your donation by clicking the button below
        %p
          =link_to 'Edit donation', edit_donation_path(@donation), :class => 'btn'